extends RefCounted
## foundation.analysis.v1: the sole shared analysis enum owner.
enum SolverStatus { SOLVED = 0, PROVEN_UNSOLVABLE = 1, BUDGET_EXCEEDED = 2, ERROR = 3 }
enum SearchMode { FIRST_SHORTEST = 0, FULL_GRAPH = 1 }
enum BudgetReason { NONE = 0, MAX_STATES = 1, MAX_EDGES = 2, MAX_DEPTH = 3, MAX_RUNTIME_MS = 4, MAX_ACTION_EVALUATIONS = 5 }
enum GraphStopReason { EXHAUSTED = 0, FIRST_GOAL = 1, BUDGET = 2, ERROR = 3 }
enum AnalysisCode {
	INVALID_LEVEL = 3000, INVALID_INITIAL_STATE = 3001, INVALID_SEARCH_POLICY = 3002,
	INVALID_SEARCH_BUDGET = 3003, KERNEL_ERROR = 3004, GOAL_ERROR = 3005,
	STATEKEY_ERROR = 3006, GRAPH_INVALID = 3007, TRACE_INVALID = 3008,
	FILTER_ERROR = 3009, VERSION_MISMATCH = 3010, LEVEL_VALIDATION_INCOMPLETE = 3011,
	ANALYSIS_OVERFLOW = 3012, REPLAY_INITIAL_UNSUPPORTED = 3013, RUNTIME_ERROR = 3014,
	RUNTIME_SOLVER_DIVERGENCE = 3015, ANALYSIS_INPUT_INVALID = 3016,
}
