extends RefCounted
## Frozen memory ABI for foundation.contract.v1. RotationAxis belongs to MATH.

enum WorldLayer { SURFACE = 0, INNER = 1 }
enum FaceDirection { FRONT = 0, BACK = 1, LEFT = 2, RIGHT = 3, TOP = 4, BOTTOM = 5 }
enum RotationIntent {
	TURN_LEFT = 0,
	TURN_RIGHT = 1,
	TIP_UP = 2,
	TIP_DOWN = 3,
	ROLL_CLOCKWISE = 4,
	ROLL_COUNTERCLOCKWISE = 5,
}
enum FaceCompatibility { SAME_NORMAL = 0, OPPOSITE_NORMAL = 1 }
enum MappingResolutionStatus { NONE = 0, UNIQUE = 1, AMBIGUOUS = 2, ERROR = 3 }
enum LightState { LIT = 0, SHADOW = 1 }
enum GlobalTransitionState { IDLE = 0, MOVING = 1, TRANSITION = 2 }
enum GlobalTransitionKind {
	NONE = 0,
	CELESTIAL = 1,
	WORLD_ROTATION = 2,
	GROUP_ROTATION = 3,
	SHIFT = 4,
	FACE_TRANSITION = 5,
}
enum FaceAxis { U_POS = 0, V_POS = 1, U_NEG = 2, V_NEG = 3 }
enum PuzzleActionKind {
	MOVE = 0,
	SHIFT_WORLD = 1,
	ROTATE_SURFACE = 2,
	ROTATE_INNER = 3,
	USE_FACE_TRANSITION = 4,
	TRIGGER_MECHANISM = 5,
	LOCAL_GROUP_ROTATE = 6,
	MOVE_CELESTIAL = 7,
}
enum CelestialOp { SET_SLOT = 0, NEXT_SLOT = 1, PREVIOUS_SLOT = 2, TOGGLE_BETWEEN = 3 }
enum ValidationSeverity { ERROR = 0, WARNING = 1, INFO = 2 }
enum ValidationCode {
	INVALID_TYPE = 1000,
	UNKNOWN_FIELD = 1001,
	MISSING_FIELD = 1002,
	INVALID_ENUM = 1003,
	INVALID_ID = 1004,
	DUPLICATE_ID = 1005,
	INVALID_REFERENCE = 1006,
	VERSION_MISMATCH = 1007,
	OFF_LATTICE = 1100,
	INVALID_ORIENTATION = 1101,
	INVALID_SURFACE_FRAME = 1102,
	INVALID_FACE = 1103,
	INVALID_ANCHOR = 1104,
	ARITHMETIC_OVERFLOW = 1105,
	SAME_WORLD_CUBE_OVERLAP = 1200,
	SEALED_WALKABLE_FACE = 1201,
	INVALID_GROUP = 1202,
	INVALID_ROTATION_EDGE = 1203,
	PLAYER_UNSAFE = 1204,
	INVALID_CELESTIAL_REFERENCE = 1300,
	SLOT_STEP_UNAVAILABLE = 1301,
	LIGHT_SOURCE_INVALID = 1302,
	NO_SHIFT_MAPPING = 1400,
	AMBIGUOUS_SHIFT_MAPPING = 1401,
	FACE_INCOMPATIBLE = 1402,
	SHIFT_REQUIRES_SHADOW = 1403,
	SHIFT_EXIT_BLOCKED = 1404,
	SHIFT_ENTRY_BLOCKED = 1405,
	GLOBAL_TRANSITION_BUSY = 1500,
	MULTIPLE_GLOBAL_MUTATIONS = 1501,
	INVALID_ACTION = 1502,
	UNAUTHORIZED_MECHANISM = 1503,
	MOVE_NOT_COMMUTATIVE = 1504,
	VALIDATION_BUDGET_EXCEEDED = 1600,
	VALIDATION_INCOMPLETE = 1601,
}
